name: Test Docker Build on PR

permissions:
  contents: read

on:
  pull_request:

jobs:
  test:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build \
            --build-arg PAYLOAD_SECRET=dummysecret \
            -t test-image ./frontend

      - name: Test Docker Image
        run: |
          docker run -d --name test test-image
          echo "Waiting for container to start. Max wait time: 120 seconds."
          for i in {1..24}; do
            if docker ps | grep test; then
              echo "Container is running!"
              exit 0
            else
              echo "- ($((i*5)) seconds elapsed)"
              sleep 5
            fi
          done
          echo "Container failed to start after 2 minutes!" && exit 1